#!/bin/sh
cores=$(grep -c ^processor /proc/cpuinfo 2>/dev/null)
[ "$cores" -eq "0" ] && cores=1
threshold="${cores:-1}.0"

echo
echo -n "  System information as of "
/bin/date
echo
/usr/bin/landscape-sysinfo --sysinfo-plugins=Load,Memory
