#!/bin/bash
# -----------------------------------------------------------------
#                 Merry Christmas (12/24 ~ 12/25)
# [C] http://chris.com/ascii/index.php?art=holiday/christmas/trees
# [R] https://github.com/BassyKuo/WelcomeMsg
# -----------------------------------------------------------------
countdown=$((1225-`date +%m%d`))
date=`date +%Y.%m.%d`
yellow_256color=220

if [[ $countdown -le 5 && $countdown -ge 2 ]]; then
	msg="  Christmas [ IN $countdown DAYS ]"
elif [[ $countdown == 1 ]]; then
	if [[ `date +%H` -le 18 ]]; then 
		msg="  Christmas [ IN $countdown DAYS ]"
	else
		msg="Happy Christmas Eve! $date"
	fi
elif [[ $countdown -le 0 ]]; then
	msg="~ MERRY CHRISTMAS // $date ~"
fi

echo -n -e "
          *\e[38;5;220m              ,
           \e[38;5;220m            _/^\\_
           \e[38;5;220m           <     >		\e[38;5;193m
     *     \e[38;5;220m            /.-.\\       \e[38;5;207m*
           \e[38;5;77m   *        \`/&\\\`                   \e[38;5;229m*
           \e[38;5;77m           ,@.*;@,
           \e[38;5;77m          /_o.I %_\\    \e[38;5;123m*\e[0m
        *  \e[38;5;77m         (\`'--:o(_@;
           \e[38;5;77m        /\`;--.,__ \`')             \e[0m*
           \e[38;5;77m       ;@\`o % O,*\`'\`&\\ 
           \e[38;5;77m *    (\`'--)_@ ;o %'()\\      \e[38;5;45m*
           \e[38;5;77m      /\`;--._\`''--._O'@;
           \e[38;5;77m     /&*,()~o\`;-.,_ \`\"\"\`)  \e[0m
     *     \e[38;5;77m     /\`,@ ;+& () o*\`;-';\\
           \e[38;5;77m    (\`\"\"--.,_0 +% @' &()\\
           \e[38;5;77m    /-.,_    \`\`''--....-'\`)  \e[38;5;219m*
          *\e[38;5;77m    /@%;o\`:;'--,.__   __.'\\
           \e[38;5;77m   ;*,&(); @ % &^;~\`\"\`o;@();         \e[38;5;259m*
           \e[38;5;77m   /(); o^~; & ().o@*&\`;&%O\\		\e[38;5;235m
    by Bass♪\e[38;5;77m  \`\"=\"==\"\"==,,,.,=\"==\"===\"\`
           \e[0m__.----.(\\-''\e[38;5;94m#####\e[0m---...___...-----._
         '\`         \\)_\`\e[38;5;94m\"\"\"\"\"\e[0m\`
                 .--' ')
               o(  )_-\\      \e[38;5;$(($yellow_256color+$countdown))m $msg \e[0m
                 \`\"\"\"\` \`
"
