#!/usr/bin/env bash

ADMIN=$1
GROUP="elsa-admin"
OTHER_GROUPS=("vglusers" "video" "render" "docker")
PASSWD=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1)

if [ "${ADMIN}" = "" ]; then
  echo "Usage: $0 <admin id>"
  exit 1
fi

sudo -v

if ! grep -q ${GROUP} /etc/group; then
  sudo groupmod --new-name ${GROUP} $(id -gn ${USER})
fi

sudo adduser ${ADMIN} \
  --ingroup ${GROUP} \
  --gecos "First Last,RoomNumber,WorkPhone,HomePhone" \
  --disabled-password
sudo usermod -aG sudo ${ADMIN}
echo "${ADMIN}:${PASSWD}" | sudo chpasswd

for OTHER_GROUP in "${OTHER_GROUPS[@]}"; do
  if grep -q ${OTHER_GROUP} /etc/group; then
    sudo usermod -aG $OTHER_GROUP $ADMIN
  fi
done

sudo mkdir /warehouse/${ADMIN}
sudo chmod 700 /warehouse/${ADMIN}
sudo mkdir /home/${ADMIN}/Warehouse
sudo chmod go-rwx /home/${ADMIN}/Warehouse
sudo chown ${ADMIN}:${GROUP} /warehouse/${ADMIN} /home/${ADMIN}/Warehouse
echo /warehouse/${ADMIN} /home/${ADMIN}/Warehouse none defaults,bind 0 0 | sudo tee -a /etc/fstab
sudo mount -a
echo "Username: ${ADMIN}"
echo "Password: ${PASSWD}"
