#!/usr/bin/env bash

STUDENT=$1
GROUP="student"
OTHER_GROUPS=("vglusers" "video" "render" "docker")
PASSWD="elsalab"

if [ "${STUDENT}" = "" ]; then
  echo "Usage: $0 <student id>"
  exit 1
fi

sudo -v

if ! grep -q ${GROUP} /etc/group; then
  sudo groupadd ${GROUP}
fi

sudo adduser ${STUDENT} \
  --ingroup ${GROUP} \
  --gecos "First Last,RoomNumber,WorkPhone,HomePhone" \
  --disabled-password
echo "${STUDENT}:${PASSWD}" | sudo chpasswd

for OTHER_GROUP in "${OTHER_GROUPS[@]}"; do
  if grep -q ${OTHER_GROUP} /etc/group; then
    sudo usermod -aG $OTHER_GROUP $STUDENT
  fi
done

sudo mkdir /warehouse/${STUDENT}
sudo chmod 700 /warehouse/${STUDENT}
sudo mkdir /home/${STUDENT}/Warehouse
sudo chmod go-rwx /home/${STUDENT}/Warehouse
sudo chown ${STUDENT}:${GROUP} /warehouse/${STUDENT} /home/${STUDENT}/Warehouse
echo /warehouse/${STUDENT} /home/${STUDENT}/Warehouse none defaults,bind 0 0 | sudo tee -a /etc/fstab
sudo mount -a
