#!/usr/bin/env bash

# Cause the script to exit on any errors
# Reference: https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -euo pipefail

if [ $# -eq 0 ]; then
  echo "Usage: $(basename $0) <available version of CUDA>"
  exit 1
fi

if [ -v CUDA_VISIBLE_DEVICES ] && [ -z "${CUDA_VISIBLE_DEVICES}" ]; then
  echo "Warning: \${CUDA_VISIBLE_DEVICES} is an empty string"
fi

VERSION=$1
PREFIX="/usr/local/cuda-"
SOURCE="${PREFIX}${VERSION}"
CUDA_LIST="$(ls -d ${PREFIX}* | xargs)"

if [ ! -d "${SOURCE}" ]; then
  echo "Info: $1 is an invalid version of CUDA"
  echo "Usage: $(basename $0) <available version of CUDA>"
  echo "       (available versions: ${CUDA_LIST//"${PREFIX}"})"
else
  ln -fns "${SOURCE}" "${CUDA_HOME}"
  echo "Info: Switch to CUDA $1"
fi
