#!/usr/bin/env bash

# Cause the script to exit on any errors
# Reference: https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -euo pipefail

VERSION=$1
PREFIX="cuda-"
SOURCE="/usr/local/${PREFIX}${VERSION}"
  
if [ ! -d "${SOURCE}" ]; then
  echo "Info: $1 is an invalid version of CUDA"   
  echo "Usage: ${FUNCNAME[0]} <available version of CUDA>"
  echo -n "       (available versions:"
  for d in $(ls /usr/local); do
    if [[ "${d}" == ${PREFIX}* ]]; then
      echo -n "  ${d#${PREFIX}}"
    fi
  done
  echo ")"
else
  ln -fns "${SOURCE}" "${CUDA_HOME}"
  echo "Info: Switch to CUDA $1"
fi
