#!/bin/sh
cores=$(grep -c ^processor /proc/cpuinfo 2>/dev/null)
[ "$cores" -eq "0" ] && cores=1
threshold="${cores:-1}.0"
load=$(/usr/bin/landscape-sysinfo --sysinfo-plugins=Load | awk '{print $3}')
load_percent=$(python3 -c "print('%3.1f%%' % (${load} / ${threshold} * 100.0))")

echo
echo -n "  System information as of "
/bin/date
echo
echo -n "  System load: ${load_percent} "
/usr/bin/landscape-sysinfo --sysinfo-plugins=Memory
