#!/bin/bash

UNDERLINE="\033[4m"
GREEN="\033[0;32m"
RESET="\033[0m"

printf "\n"
printf "  For more information:\n"
printf "    ${GREEN}http://bit.ly/elsa-lab-info${RESET}\n"
printf "\n"
printf "  If you have any problem, please contact:\n"
printf "    ${GREEN}https://t.me/yu020009${RESET} or ${GREEN}kychang@elsa-lab-slack${RESET}\n"
