#!/bin/sh

BF="\033[1m"
CC="\033[0m"
PW=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1)

printf "Random Generated VNC Password: ${BF}${PW}${CC}\n"

[ ! -d ${HOME}/.vnc ] && mkdir -p ${HOME}/.vnc
echo ${PW} | /usr/bin/tigervncpasswd -f > ${HOME}/.vnc/passwd

chmod 600 ${HOME}/.vnc/passwd
