#!/usr/bin/env bash

BF="\033[1m"
CC="\033[0m"
PW=$(shuf -zer -n8 {A..Z} {a..z} {0..9} | tr -d '\0')

printf "Random Generated VNC Password: ${BF}${PW}${CC}\n"

[ ! -d ${HOME}/.vnc ] && mkdir -p ${HOME}/.vnc
echo ${PW} | /usr/bin/tigervncpasswd -f > ${HOME}/.vnc/passwd

chmod 600 ${HOME}/.vnc/passwd
