#!/usr/bin/env bash

# Cause the script to exit on any errors
# Reference: https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -euo pipefail

RELEASE=$(lsb_release -r | awk '{print $NF}')
VNC_DOT="${HOME}/.vnc"
PASSWD="${VNC_DOT}/passwd"
XSTARTUP="${VNC_DOT}/xstartup"

[ ! -d ${VNC_DOT} ] && mkdir -p ${VNC_DOT}
[ ! -f ${PASSWD} ] && vnc-pwdgen
[ ! -f ${XSTARTUP} ] && cat << 'EOF' > ${XSTARTUP}
#!/bin/sh

export PATH="${HOME}/.cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"

unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

vncconfig -nowin &

# The newer versions of tigervncserver expects the ~/.vnc/xstartup script to stay in foreground. 
# Reference: https://askubuntu.com/a/1387849
startxfce4

EOF
chmod +x ${XSTARTUP}

if [ ${RELEASE} == "16.04" ]; then
  tigervncserver $@
else
  tigervncserver -localhost no $@
fi
